namespace: storage
name: hpe3par
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/storage.hpe3par.git
documentation: https://github.com/coll-test/storage.hpe3par/tree/master/docs
homepage: https://github.com/coll-test/storage.hpe3par
issues: https://github.com/coll-test/storage.hpe3par/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
